name: 'dbt_music_analytics'
version: '1.0.0'
config-version: 2

profile: 'dbt_music_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_music_analytics:

    staging:
      +materialized: table
      +schema: STG

    dw:
      +materialized: table
      +schema: DW

    mart:
      +materialized: table
      +schema: MART