USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MUSIC_DB;
CREATE SCHEMA IF NOT EXISTS MUSIC_DB.RAW;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE MUSIC_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE ITUNES_STAGE;

CREATE OR REPLACE TABLE ITUNES_TRACKS_RAW (
    TRACK_ID STRING,
    ARTIST_ID STRING,
    COLLECTION_ID STRING,
    ARTIST_NAME STRING,
    COLLECTION_NAME STRING,
    TRACK_NAME STRING,
    PRIMARY_GENRE_NAME STRING,
    TRACK_PRICE FLOAT,
    CURRENCY STRING,
    RELEASE_DATE STRING,
    COUNTRY STRING,
    INGESTED_AT STRING,
    SOURCE_TERM STRING
);
